import React, { useEffect } from "react";
import { useLocation } from "react-router-dom";

const Privacy: React.FC = () => {
  const { hash } = useLocation();

  useEffect(() => {
    if (hash === "#cookie-policy") {
      const el = document.getElementById("cookie-policy");
      if (el) {
        const rect = el.getBoundingClientRect();
        const currentScroll = window.scrollY || window.pageYOffset;
        const headerOffset = 96;
        const targetY = rect.top + currentScroll - headerOffset;

        window.scrollTo({
          top: targetY,
          behavior: "smooth",
        });
      }
    }
  }, [hash]);

  return (
    <main className="min-h-screen bg-slate-100 text-slate-900">
      <section className="max-w-5xl mx-auto px-6 py-16">
        <h1 className="text-3xl md:text-4xl font-semibold mb-4">
          Privacy Policy
        </h1>
        <p className="text-sm text-slate-500 mb-10">
          Effective date: June 1, 2025
        </p>

        <div className="space-y-6 text-sm leading-relaxed text-slate-800">
          <p>
            InfraQo is a brand and operating division of QoLogic LLC, and together
            with its affiliates, subsidiaries, and agents (“InfraQo,” “we,” “us,”
            or “our”), operates the infraqo.com website and provides related structured
            cabling, network infrastructure, IT support, and managed services
            (collectively, the “Services”).
          </p>
          <p>
            This Privacy Policy informs you of our policies regarding the
            collection, use, and disclosure of information, including personal
            data, when you use our website (the “Site”) or otherwise interact
            with us, and the choices you have associated with that information.
          </p>
          <p>
            By accessing or using the Site, submitting information through it,
            or engaging us to provide Services, you agree to the collection and
            use of information in accordance with this Privacy Policy. Unless
            otherwise defined here, terms used in this Privacy Policy have the
            same meanings as in our Terms of Service.
          </p>

          <h2 className="text-xl font-semibold mt-10">1. Definitions</h2>
          <p>
            <span className="font-semibold">“Personal Data”</span> means any
            information relating to an identified or identifiable natural
            person. This may include, for example, a name, email address, phone
            number, business contact details, or other identifiers that can be
            used to contact or identify an individual.
          </p>
          <p>
            <span className="font-semibold">“Business Data”</span> means
            information relating to your company, organization, facilities,
            systems, or infrastructure that you provide to us or that we access
            in the course of delivering the Services. This can include network
            diagrams, device inventories, configuration details, site plans, and
            similar operational information.
          </p>
          <p>
            <span className="font-semibold">“Technical Data”</span> means
            system-level, device-level, and network-level information collected
            during the provision of our Services, including logs, performance
            metrics, telemetry, monitoring data, and similar diagnostic
            information.
          </p>
          <p>
            <span className="font-semibold">“Usage Data”</span> means data
            collected automatically and generated by the use of the Site or from
            the Site infrastructure itself (for example, pages visited, time
            spent on pages, browser type, and other diagnostic data).
          </p>
          <p>
            <span className="font-semibold">“Cookies”</span> means small text
            files placed on your device that may contain an anonymous unique
            identifier and store certain information about your use of the Site.
          </p>
          <p>
            <span className="font-semibold">“Data Controller”</span> means the
            person or entity that determines the purposes for which and the
            manner in which Personal Data is processed. For purposes of this Privacy
            Policy, QoLogic LLC, operating through its InfraQo brand, is the Data
            Controller of the Personal Data we collect through the Site or in
            connection with the Services, except where otherwise noted in a separate
            written agreement.
          </p>
          <p>
            <span className="font-semibold">“Data Processor”</span> or{" "}
            <span className="font-semibold">“Service Provider”</span> means any
            person or entity (other than an employee of the Data Controller)
            that processes data on behalf of the Data Controller. We may engage
            various Service Providers to process data more effectively.
          </p>
          <p>
            <span className="font-semibold">“Data Subject”</span> means any
            living individual who is the subject of Personal Data.
          </p>
          <p>
            <span className="font-semibold">“User”</span> means the individual
            using our Site or otherwise interacting with InfraQo. The User
            corresponds to the Data Subject, who is the subject of Personal
            Data.
          </p>

          <h2 className="text-xl font-semibold mt-10">
            2. Information We Collect
          </h2>
          <p>
            We collect several types of information for various purposes to
            provide and improve the Site and Services.
          </p>

          <h3 className="text-base font-semibold mt-6">
            2.1 Information You Provide Directly
          </h3>
          <p>
            While using our Site or engaging our Services, we may ask you to
            provide certain information, including:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>First and last name</li>
            <li>Company or organization name</li>
            <li>Job title or role</li>
            <li>Email address</li>
            <li>Telephone number</li>
            <li>Business mailing address and service location(s)</li>
            <li>
              Details about your network, cabling, infrastructure, and related
              projects
            </li>
            <li>Any other information you choose to provide</li>
          </ul>
          <p>
            If you subscribe to a newsletter or other marketing communications,
            we will also collect the information you submit in those forms
            (typically name and email address).
          </p>

          <h3 className="text-base font-semibold mt-6">2.2 Usage Data</h3>
          <p>
            We may also collect information on how the Site is accessed and
            used. This Usage Data may include:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>Internet Protocol (IP) address</li>
            <li>Browser type and version</li>
            <li>Device type and operating system</li>
            <li>Pages visited and time and date of visits</li>
            <li>Time spent on pages and links clicked</li>
            <li>Referring/exit pages</li>
            <li>Unique device identifiers and other diagnostic data</li>
          </ul>

          <h3 id="cookie-policy" className="text-base font-semibold mt-6">
            2.3 Cookies and Tracking Technologies (Cookie Policy)
          </h3>
          <p>
            We may use Cookies and similar tracking technologies (such as tags,
            scripts, and pixels) to track activity on the Site and hold certain
            information. This section also serves as our Cookie Policy and
            explains how and why we use Cookies and similar technologies on the
            Site. You can instruct your browser to refuse all Cookies or to
            indicate when a Cookie is being sent. However, if you do not accept
            Cookies, some portions of the Site may not function as intended.
          </p>
          <p>Examples of Cookies we may use include:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Session Cookies – to operate our Site.</li>
            <li>
              Preference Cookies – to remember your preferences and various
              settings.
            </li>
            <li>Security Cookies – for security and authentication purposes.</li>
            <li>Analytics Cookies – to understand how visitors use the Site.</li>
            <li>
              Advertising or Conversion Cookies – if we run digital advertising
              campaigns and measure their effectiveness.
            </li>
          </ul>

          <h3 className="text-base font-semibold mt-6">
            2.4 Remote Monitoring, Managed Services, and Technical Data
          </h3>
          <p>
            In connection with network monitoring, managed services, or ongoing
            support, we may collect or access Technical Data and Business Data,
            including:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>Device and system identifiers</li>
            <li>Network topology and configuration information</li>
            <li>System and application logs</li>
            <li>Performance and uptime metrics</li>
            <li>Security, alert, or event data</li>
            <li>
              Asset inventories, serial numbers, and deployment details
            </li>
          </ul>
          <p>
            Any such access information is used solely for authorized service delivery,
            limited to personnel with a legitimate need to know, and handled in accordance
            with applicable confidentiality and security obligations.
          </p>
          <p>
            This information is used strictly for the purposes of delivering,
            maintaining, securing, and improving the Services you have
            requested, in accordance with this Policy and any applicable
            agreements between us.
          </p>

          <h3 className="text-base font-semibold mt-6">
            2.5 Information from Third Parties
          </h3>
          <p>
            We may receive information about you from third parties, such as
            referral partners, public sources, or Service Providers (for
            example, analytics or CRM platforms).
          </p>

          <h2 className="text-xl font-semibold mt-10">3. Use of Data</h2>
          <p>InfraQo uses the collected data for various purposes, including:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>To provide, operate, and maintain the Site and Services</li>
            <li>
              To process and respond to your inquiries and requests for quotes
            </li>
            <li>
              To plan, design, implement, and support cabling and
              network-related solutions
            </li>
            <li>To notify you about changes to our Site or Services</li>
            <li>
              To allow you to participate in interactive features of our Site
              when you choose to do so
            </li>
            <li>To provide customer support and technical assistance</li>
            <li>
              To monitor the usage of the Site and Services and gather analysis
              and valuable information so that we can improve them
            </li>
            <li>
              To detect, prevent, and address technical issues and security
              incidents
            </li>
            <li>
              To send newsletters, marketing or promotional materials, and other
              information that may be of interest to you, where permitted by law
            </li>
            <li>
              To comply with legal, regulatory, and contractual obligations and
              enforce our rights
            </li>
          </ul>
          <p>
            We may use anonymized or aggregated data (which does not identify
            individuals) for purposes such as analytics, industry insights,
            capacity planning, or improving our offerings. We do not sell
            Personal Data.
          </p>

          <h2 className="text-xl font-semibold mt-10">
            4. Legal Bases for Processing
          </h2>
          <p>
            If you are located in the EEA, UK, or similar jurisdiction that
            requires a legal basis for processing, InfraQo processes your
            Personal Data on one or more of the following bases:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>
              The performance of a contract with you or to take steps at your
              request prior to entering into a contract
            </li>
            <li>
              Our legitimate business interests (for example, to operate the
              Site, respond to inquiries, improve our Services, maintain
              security, and grow our business)
            </li>
            <li>Compliance with a legal obligation</li>
            <li>Your consent, where required by law</li>
          </ul>

          <h2 className="text-xl font-semibold mt-10">5. Retention of Data</h2>
          <p>
            InfraQo will retain Personal Data and Business Data only for as long
            as is reasonably necessary for the purposes set out in this Privacy
            Policy, or as required to provide the Services, comply with
            applicable laws, resolve disputes, and enforce our legal agreements
            and policies.
          </p>

          <h2 className="text-xl font-semibold mt-10">6. Transfer of Data</h2>
          <p>
            Your information, including Personal Data, may be transferred to and
            maintained on servers located outside of your state, province, or
            country. By providing information to us, you consent to such
            transfers, subject to applicable law.
          </p>

          <h2 className="text-xl font-semibold mt-10">7. Disclosure of Data</h2>
          <h3 className="text-base font-semibold mt-4">
            7.1 Service Providers and Business Partners
          </h3>
          <p>
            We may employ third-party companies and individuals to facilitate
            our Site and Services, perform Service-related functions, or assist
            us in analyzing how our Site and Services are used. These third
            parties have access to Personal Data and Business Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </p>

          <h3 className="text-base font-semibold mt-4">
            7.2 Legal Requirements and Protection
          </h3>
          <p>
            InfraQo may disclose your information in the good faith belief that
            such action is necessary to comply with a legal obligation, protect
            and defend our rights or property, prevent or investigate possible
            wrongdoing, protect the personal safety of users or the public, or
            protect against legal liability.
          </p>

          <h3 className="text-base font-semibold mt-4">
            7.3 Business Transfers
          </h3>
          <p>
            If InfraQo is involved in a merger, acquisition, or asset sale, your
            information may be transferred as part of that transaction.
          </p>

          <h2 className="text-xl font-semibold mt-10">8. Security of Data</h2>
          <p>
            We implement commercially reasonable safeguards designed to protect
            your data. However, no method of transmission over the Internet or
            electronic storage is 100% secure. While we strive to protect your
            data, we cannot guarantee its absolute security.
          </p>

          <h2 className="text-xl font-semibold mt-10">9. Your Rights</h2>
          <p>
            Depending on your jurisdiction, you may have rights regarding your
            Personal Data, including rights of access, correction, deletion,
            restriction, objection, and data portability, as well as the right
            to withdraw consent where processing is based on consent. Residents
            of certain U.S. states may have additional rights under state
            privacy laws.
          </p>
          <p>
            To exercise these rights, contact us at{" "}
            <a
              href="mailto:support@infraqo.com"
              className="font-mono text-blue-700 hover:text-blue-800 underline underline-offset-2"
            >
              support@infraqo.com
            </a>
            . We may need to verify your identity before responding.
          </p>

          <h2 className="text-xl font-semibold mt-10">
            10. Children’s Privacy
          </h2>
          <p>
            The Site and Services are intended for business users and are not
            directed to children under 18. We do not knowingly collect Personal
            Data from anyone under 18. If you believe we have collected such
            information, please contact us so we can take appropriate steps to
            delete it.
          </p>

          <h2 className="text-xl font-semibold mt-10">
            11. Third-Party Sites and Services
          </h2>
          <p>
            Our Site may contain links to third-party websites or services that
            are not operated by InfraQo. We are not responsible for the content,
            privacy policies, or practices of any third-party sites or services.
            We encourage you to review the privacy policy of every site you
            visit.
          </p>

          <h2 className="text-xl font-semibold mt-10">
            12. Changes to This Privacy Policy
          </h2>
          <p>
            We may update our Privacy Policy from time to time. We will post the
            updated Privacy Policy on this page and update the effective date at
            the top. When required by law, we will provide additional notice.
          </p>

          <h2 className="text-xl font-semibold mt-10">13. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or our handling
            of your information, please contact us:
          </p>
          <ul className="list-disc list-inside space-y-1">
            <li>
              Email:{" "}
              <a
                href="mailto:support@infraqo.com"
                className="font-mono text-blue-700 hover:text-blue-800 underline underline-offset-2"
              >
                support@infraqo.com
              </a>
            </li>
            <li>
              Telephone:{" "}
              <a
                href="tel:17205154843"
                className="text-blue-700 hover:text-blue-800 underline underline-offset-2"
              >
                720-515-4843
              </a>
            </li>
            <li>
              Mailing address: 411 W Platte Ave Ste A142, Fort Morgan, CO 80701
            </li>
          </ul>
        </div>
      </section>
    </main>
  );
};

export default Privacy;
